GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/6a059546b6aaf549b7d9c0b8

###


GET http://localhost:3001/api/persons/6a059546b6aaf549b7d9c0b8

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "سلاسم Hasllas",
    "number": "123456789"
}
